package br.com.usinasantafe.cav.lib

enum class StatusSend { STARTED, SEND, SENT }
enum class Errors { FIELD_EMPTY, TOKEN, UPDATE, EXCEPTION, INVALID, NON_EXISTENT_LOCAL, NON_EXISTENT_NATURE, NON_EXISTENT_TYPE_ACCIDENT, NON_EXISTENT_DATA_LOCAL, NON_EXISTENT_VEHICLE_OWN }
enum class TypeButton { NUMERIC, CLEAN, OK, UPDATE }

enum class LevelUpdate { RECOVERY, CLEAN, SAVE, GET_TOKEN, SAVE_TOKEN, FINISH_UPDATE_INITIAL, FINISH_UPDATE_COMPLETED }

enum class Option { INSERT, EDIT }
enum class FlowNote { EQUIP, EQUIP_SEC, COLAB, PASSENGER_COLAB, VEHICLE, DRIVER, PASSENGER_EXTERNAL, INVOLVED_EXTERNAL, WITNESS_EXTERNAL, INVOLVED_COLAB, WITNESS_COLAB }
enum class TypeVehicle { OWN, INVOLVED }
enum class TypePeople { INVOLVED, WITNESS }

enum class State(val id: Int) {
    UNHARMED(1),
    INJURED(2),
    DEAD(3)
}